### ISSUE TITLE
Consider publishing a release instead of pushing binaries directly to branches.

### ISSUE THREAD

**Issue by jamesbt365** [ReSuKiii/letmeplay#1]
There is functionally no reason to do it the way you have, and having binaries within git repos is highly discouraged.

**Comment by ReSuKiii** [comment]
consider reading the post on media on why i did this, casual users get lost on github, i did this to make things easier

**Comment by jamesbt365** [comment]
> consider reading the post on media on why i did this, casual users get lost on github, i did this to make things easier

And instead you choose to check binaries into version control which can lead to diverted and unclear versioning? 

# Issues with Current Approach

- Ambiguity is added over versioning
- bloated repository sizes
- Unclear setup instructions
- Generally poor user experience

I can tell you have never shipped software before, so you generally don't know the flow of it, but you are letting users shoot themselves in the foot.

You can link to GitHub releases, there is no reason for users coming from sites you have linked it to even look at the rest of the repository, even still, the clear releases section on the right alongside instructions you have put in the `README.md` should point in the right places.

The instructions you have provided *as of right now* **do not** explain everything.

This is a really backwards way of attempting to improve user experience, you haven't even provided fool-proof setup instructions. This is far less intuitive then click one button and done.

**Your current listed** install process is *download the folder* (which you haven't explained how to do), extract it and run the exe file.

Your current install method requires users to click an ambiguous code button, which again, you have **not** referenced at all.

If you actually care about user experience then you should do things properly, or at least *explain* how to do what you are telling them to do instead of leaving them in the dark and letting them shoot themselves in the foot.

This is why I'm recommending that you *use* releases. Look at other software, they do not ship this way, they do not have problems shipping releases. You are making this a user experience and dev nightmare.

# Recommendations
- Push releases for each iteration of your software.
- Update your instructions to point to the release, inside the description of your release you can even link directly to the asset file if that makes things any easier for users.
 - This way you can even drop the zip file and leave them with just the exe if you want.

I just don't understand the motive behind *not* pushing releases. This is not easier at all. I have spoken to others about this in the past and it just hardly ever is the better idea to push binaries directly to repos.

You can write an *actually usable* section in your README to provide an objectively better user experience. 

You are adding a world full of other issues to mitigate an issue that doesn't exist.

I have helped plenty of users (coming from an OpenTabletDriver dev here) that hardly know how to use a computer with instructions *linked on the release page* and we have had no issues with properly written sections.

# Closing this issue properly.

You shouldn't close issues as completed if they are not completed. GitHub offers lots of great tooling (releases included)!

If you still don't care to provide a good UX then change the closing reason to [not planned](https://docs.github.com/en/issues/tracking-your-work-with-issues/closing-an-issue). Remove ambiguity everywhere!

Bonus points if you attach the won't fix label!

Don't take this as harsh but you wanted suggestions and you aren't listening to them.
